package main

import (
	"fmt"

	"github.com/jameschenn/smashbrosgo-api/models"
	"github.com/jameschenn/smashbrosgo-api/utils"
	"gorm.io/gorm"
)

var characters = []models.Character{
	// {
	// 	Name:
	// 	Series:
	// 	FirstAppearance:
	// 	Description:
	// 	Tier:
	// 	Weight:
	// 	Speed:
	// 	NeutralB:
	// 	UpB:
	// 	SideB:
	// 	DownB:
	// 	Final_Smash:
	// 	Image_URL:
	// },
	{
		Name:            "Mario",
		Series:          "Super Mario",
		FirstAppearance: "Donkey Kong",
		Description:     "Mario is an all-around fighter who uses his wide variety of techniques to respond to any situation. In Super Smash Bros. Ultimate, he shows up in his wedding tux and builder outfit, and Cappy even makes an appearance!",
		Tier:            "A",
		Weight:          98,
		Speed:           1.76,
		NeutralB:        "Fireball",
		UpB:             "Super Jump Punch",
		SideB:           "Cape",
		DownB:           "F.L.U.D.D",
		Final_Smash:     "Mario Finale",
		Image_URL:       "https://ssb.wiki.gallery/images/4/44/Mario_SSBU.png",
	},
	{
		Name:            "Donkey Kong",
		Series:          "Donkey Kong",
		FirstAppearance: "Donkey Kong",
		Description:     "His charged punch is one of the strongest attacks in the game! In Super Smash Bros. Ultimate, his Final Smash has been updated from Konga Beat to a flurry of punches!",
		Tier:            "D+",
		Weight:          127,
		Speed:           1.873,
		NeutralB:        "Giant Punch",
		UpB:             "Spinning Kong",
		SideB:           "Headbutt",
		DownB:           "Hand Slap",
		Final_Smash:     "Jungle Rush",
		Image_URL:       "https://ssb.wiki.gallery/images/c/c9/Donkey_Kong_SSBU.png",
	},
	{
		Name:            "Link",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda",
		Description:     "Link has been redesigned to match his appearance in The Legend of Zelda: Breath of the Wild. He can now pick up arrows he's fired, and his bombs have been upgraded to remote bombs, so you can set them off when the timing is just right!",
		Tier:            "C+",
		Weight:          104,
		Speed:           1.534,
		NeutralB:        "Bow and Arrows",
		UpB:             "Spin Attack",
		SideB:           "Boomerang",
		DownB:           "Remote Bomb",
		Final_Smash:     "Ancient Bow and Arrow",
		Image_URL:       "https://ssb.wiki.gallery/images/8/84/Link_SSBU.png",
	},
	{
		Name:            "Samus",
		Series:          "Metroid",
		FirstAppearance: "Metroid",
		Description:     "With her Charge Shot, Missile, and Bomb, Samus has three different projectiles to keep her opponents in check from a distance. When fully charged up, her Charge Shot is quite powerful. For her Final Smash, she launches a wide laser beam that can be moved up and down!",
		Tier:            "A",
		Weight:          108,
		Speed:           1.654,
		NeutralB:        "Charge Shot",
		UpB:             "Screw Attack",
		SideB:           "Missile",
		DownB:           "Bomb",
		Final_Smash:     "Zero Laser",
		Image_URL:       "https://ssb.wiki.gallery/images/0/03/Samus_SSBU.png",
	},
	{
		Name:            "Yoshi",
		Series:          "Yoshi",
		FirstAppearance: "Super Mario World",
		Description:     "Yoshi is all about egg-related moves, like throwing eggs, swallowing opponents and turning them into eggs, or turning into an egg and charging toward an opponent. With a high jump, recovery is a piece of cake for Yoshi! And for his Final Smash, a Yoshi army stampedes through the stage.",
		Tier:            "A+",
		Weight:          104,
		Speed:           2.046,
		NeutralB:        "Egg Lay",
		UpB:             "Egg Throw",
		SideB:           "Egg Roll",
		DownB:           "Yoshi Bomb",
		Final_Smash:     "Stampede!",
		Image_URL:       "https://ssb.wiki.gallery/images/8/8d/Yoshi_SSBU.png",
	},
	{
		Name:            "Kirby",
		Series:          "Kirby",
		FirstAppearance: "Kirby's Dream Land",
		Description:     "Kirby's ability to copy fighters is totally unique! While he is light and can be launched easily, he can also jump up to five times in the air, so he has great recovery. Look for his new Stone transformation, too.",
		Tier:            "D-",
		Weight:          79,
		Speed:           1.727,
		NeutralB:        "Inhale",
		UpB:             "Final Cutter",
		SideB:           "Hammer Flip",
		DownB:           "Stone",
		Final_Smash:     "Ultra Sword",
		Image_URL:       "https://ssb.wiki.gallery/images/0/07/Kirby_SSBU.png",
	},
	{
		Name:            "Fox",
		Series:          "Star Fox",
		FirstAppearance: "Star Fox",
		Description:     `He can overwhelm his opponents with his quick movements, and his specials don't leave him open for counterattacks. His costume and voice have been redone to match his appearance in Star Fox Zero. This Fox is brand new! "Come on!`,
		Tier:            "S-",
		Weight:          77,
		Speed:           2.402,
		NeutralB:        "Blaster",
		UpB:             "Fire Fox",
		SideB:           "Fox Illusion",
		DownB:           "Reflector",
		Final_Smash:     "Team Star Fox",
		Image_URL:       "https://ssb.wiki.gallery/images/2/2f/Fox_SSBU.png",
	},
	{
		Name:            "Pikachu",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "This fierce fighter uses electric moves like Thunder Jolt and Thunder. Pikachu Libre is one of the alternate costumes, and you can tell she's female by the shape of her tail.",
		Tier:            "A",
		Weight:          79,
		Speed:           2.039,
		NeutralB:        "Thunder Jolt",
		UpB:             "Quick Attack",
		SideB:           "Skull Bash",
		DownB:           "Thunder",
		Final_Smash:     "Volt Tackle",
		Image_URL:       "https://ssb.wiki.gallery/images/9/93/Pikachu_SSBU.png",
	},
	{
		Name:            "Luigi",
		Series:          "Super Mario",
		FirstAppearance: "Mario Bros.",
		Description:     `He can jump higher than his older brother, Mario. His Up Special, Super Jump Punch, will gain maximum damage and launching power when hitting the opponent right at the start. It truly is a "Special" move. He also uses his new Poltergust for his throw!`,
		Tier:            "B+",
		Weight:          97,
		Speed:           1.65,
		NeutralB:        "Fireball",
		UpB:             "Super Jump Punch",
		SideB:           "Green Missile",
		DownB:           "Luigi Cyclone",
		Final_Smash:     "Poltergust G-00",
		Image_URL:       "https://www.ssbwiki.com/images/b/bb/Luigi_SSBU.png",
	},
	{
		Name:            "Ness",
		Series:          "EarthBound",
		FirstAppearance: "EarthBound",
		Description:     `Ness has a variety of moves, from long-range attacks using psychic powers known as "PSI," to short-range attacks with his bat and yo-yo. Ness can also unleash PK Thunder, a guided attack that can launch him like a rocket or help him recover!`,
		Tier:            "B-",
		Weight:          94,
		Speed:           1.609,
		NeutralB:        "PK Flash",
		UpB:             "PK Thunder",
		SideB:           "PK Fire",
		DownB:           "PSI Magnet",
		Final_Smash:     "PK Starstorm",
		Image_URL:       "https://ssb.wiki.gallery/images/8/82/Ness_SSBU.png",
	},
	{
		Name:            "Captain Falcon",
		Series:          "F-Zero",
		FirstAppearance: "F-Zero",
		Description:     "A fighter that possesses both speed and power! But in exchange, he is frequently left open. Being able to successfully land his neutral special, Falcon Punch, can greatly influence the battle in multiplayer matches.",
		Tier:            "B-",
		Weight:          104,
		Speed:           2.552,
		NeutralB:        "Falcon Punch",
		UpB:             "Falcon Dive",
		SideB:           "Raptor Boost",
		DownB:           "Falcon Kick",
		Final_Smash:     "Blue Falcon",
		Image_URL:       "https://ssb.wiki.gallery/images/d/da/Captain_Falcon_SSBU.png",
	},
	{
		Name:            "Jigglypuff",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "Jigglypuff can jump 5 times in the air and can move faster in the air than on the ground. Use Jigglypuff's great aerial ability to overwhelm your opponent! If you manage to land the down special Rest, you can powerfully launch your opponent.",
		Tier:            "C+",
		Weight:          68,
		Speed:           1.271,
		NeutralB:        "Rollout",
		UpB:             "Sing",
		SideB:           "Pound",
		DownB:           "Rest",
		Final_Smash:     "Puff Up",
		Image_URL:       "https://ssb.wiki.gallery/images/6/6a/Jigglypuff_SSBU.png",
	},
	{
		Name:            "Peach",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros.",
		Description:     "THE super princess. Watch out for her powerful kicks while she's airborne. Using her down special, she picks vegetables and throws them at her opponents. Sometimes she even gets items...like a Bob-omb!",
		Tier:            "S-",
		Weight:          89,
		Speed:           1.595,
		NeutralB:        "Toad",
		UpB:             "Peach Parasol",
		SideB:           "Peach Bomber",
		DownB:           "Vegetable",
		Final_Smash:     "Peach Blossom",
		Image_URL:       "https://www.ssbwiki.com/images/7/74/Peach_SSBU.png",
	},
	{
		Name:            "Bowser",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros.",
		Description:     "Who's the greatest nemesis of all!? It's King Bowser! In Super Smash Bros. his power and weight make him a reliable fighter. Use his Fire Breath to keep opponents at bay, then use his damaging attacks to launch them off the stage! He transforms into Giga Bowser for his Final Smash and delivers a super powerful punch!",
		Tier:            "C+",
		Weight:          135,
		Speed:           1.971,
		NeutralB:        "Fire Breath",
		UpB:             "Whirling Fortress",
		SideB:           "Flying Slam",
		DownB:           "Bowser Bomb",
		Final_Smash:     "Giga Bowser Punch",
		Image_URL:       "https://www.ssbwiki.com/images/4/49/Bowser_SSBU.png",
	},
	{
		Name:            "Ice Climbers",
		Series:          "Ice Climber",
		FirstAppearance: "Ice Climber",
		Description:     "Back in the battle after a ten-year absence! There are two of them, so does that make them twice as strong as other fighters?",
		Tier:            "C+",
		Weight:          92,
		Speed:           1.53,
		NeutralB:        "Ice Shot",
		UpB:             "Belay",
		SideB:           "Squall Hammer",
		DownB:           "Blizzard",
		Final_Smash:     "Iceberg",
		Image_URL:       "https://ssb.wiki.gallery/images/1/12/Ice_Climbers_SSBU.png",
	},
	{
		Name:            "Sheik",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda: Ocarina of Time",
		Description:     "Now Sheik joins the battle wearing the Sheikah costume from The Legend of Zelda: Breath of the Wild. Keep the pressure on your opponent by using his speedy dash to quickly close in on (or get away from) your opponent!",
		Tier:            "B+",
		Weight:          78,
		Speed:           2.42,
		NeutralB:        "Needle Storm",
		UpB:             "Vanish",
		SideB:           "Burst Grenade",
		DownB:           "Bouncing Fish",
		Final_Smash:     "Sheikah Dance",
		Image_URL:       "https://ssb.wiki.gallery/images/0/00/Sheik_SSBU.png",
	},
	{
		Name:            "Zelda",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda",
		Description:     `You might recognize Zelda's look from The Legend of Zelda: A Link Between Worlds game. In battle she uses magical moves to reflect and teleport, and for her Final Smash, she seals her opponents away in the Triforce of Wisdom. If an opponent has 100% damage or more, they will be instantly KO'd!`,
		Tier:            "D-",
		Weight:          85,
		Speed:           1.43,
		NeutralB:        "Nayru's Love",
		UpB:             "Farore's Wind",
		SideB:           "Din's Fire",
		DownB:           "Phantom Slash",
		Final_Smash:     "Triforce of Wisdom",
		Image_URL:       "https://ssb.wiki.gallery/images/c/c8/Zelda_SSBU.png",
	},
	{
		Name:            "Dr. Mario",
		Series:          "Super Mario",
		FirstAppearance: "Dr. Mario",
		Description:     "He has more attack and launch power than Mario, but his jump and recovery is not as good. Pro tip: You can repeatedly press the B button when using his down special, Dr. Tornado, to float a bit!",
		Tier:            "D-",
		Weight:          98,
		Speed:           1.5375712,
		NeutralB:        "Megavitamins",
		UpB:             "Super Jump Punch",
		SideB:           "Super Sheet",
		DownB:           "Dr. Tornado",
		Final_Smash:     "Doctor Finale",
		Image_URL:       "https://ssb.wiki.gallery/images/3/3f/Dr._Mario_SSBU.png",
	},
	{
		Name:            "Pichu",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Gold and Silver",
		Description:     "Pichu is back after 17 years! Pichu's electric attacks have greater range and do more damage than its other attack types, but they also damage Pichu.",
		Tier:            "C+",
		Weight:          62,
		Speed:           1.892,
		NeutralB:        "Thunder Jolt",
		UpB:             "Agility",
		SideB:           "Skull Bash",
		DownB:           "Thunder",
		Final_Smash:     "Volt Tackle",
		Image_URL:       "https://ssb.wiki.gallery/images/c/c1/Pichu_SSBU.png",
	},
	{
		Name:            "Falco",
		Series:          "Star Fox",
		FirstAppearance: "Star Fox",
		Description:     "He's a talented aerial fighter with amazing jumping ability, but Falco is a bit slower on the ground. His Final Smash is an all-out attack using an unorthodox formation of Arwings!",
		Tier:            "B+",
		Weight:          82,
		Speed:           1.619,
		NeutralB:        "Blaster",
		UpB:             "Fire Bird",
		SideB:           "Falco Phantasm",
		DownB:           "Reflector",
		Final_Smash:     "Team Star Fox",
		Image_URL:       "https://ssb.wiki.gallery/images/8/80/Falco_SSBU.png",
	},
	{
		Name:            "Marth",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem: Shadow Dragon and the Blade of Light",
		Description:     "Marth is an exceptional swordfighter with a long reach. He'll do the most damage with attacks using the tip of his sword, so spacing is an important factor.",
		Tier:            "C+",
		Weight:          90,
		Speed:           1.964,
		NeutralB:        "Shield Breaker",
		UpB:             "Dolphin Slash",
		SideB:           "Dancing Blade",
		DownB:           "Counter",
		Final_Smash:     "Critical Hit",
		Image_URL:       "https://www.ssbwiki.com/images/e/e9/Marth_SSBU.png",
	},
	{
		Name:            "Lucina",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem Awakening",
		Description:     "Lucina is Marth's echo fighter, so she shares most of her standard and special attacks with Marth. However, while Marth's attacks are more powerful when made with the tip of his blade, Lucina's attacks just as powerful whether you use the tip or the base of the sword.",
		Tier:            "A-",
		Weight:          90,
		Speed:           1.964,
		NeutralB:        "Shield Breaker",
		UpB:             "Dolphin Slash",
		SideB:           "Dancing Blade",
		DownB:           "Counter",
		Final_Smash:     "Critical Hit",
		Image_URL:       "https://ssb.wiki.gallery/images/d/dc/Lucina_SSBU.png",
	},
	{
		Name:            "Young Link",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda: Ocarina of Time",
		Description:     "He's back after 17 years! Young Link is faster than Link but he's also lighter, making him easier to launch.",
		Tier:            "B+",
		Weight:          88,
		Speed:           1.749,
		NeutralB:        "Fire Arrow",
		UpB:             "Spin Attack",
		SideB:           "Boomerang",
		DownB:           "Bomb",
		Final_Smash:     "Triforce Slash",
		Image_URL:       "https://ssb.wiki.gallery/images/8/8a/Young_Link_SSBU.png",
	},
	{
		Name:            "Ganondorf",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda",
		Description:     "His new design matches his appearance in The Legend of Zelda: Ocarina of time! Now he uses his sword for all of his smash attacks. He's a bit slimmer than he was before, but his warlock punch is devastating! For his final smash he transforms into Ganon The Demon King and quickly charges forward.",
		Tier:            "E-",
		Weight:          118,
		Speed:           1.34,
		NeutralB:        "Warlock Punch",
		UpB:             "Dark Dive",
		SideB:           "Flame Choke",
		DownB:           "Wizard's Foot",
		Final_Smash:     "Ganon, The Demon King",
		Image_URL:       "https://www.ssbwiki.com/images/9/91/Ganondorf_SSBU.png",
	},
	{
		Name:            "Mewtwo",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "A Legendary Pokémon known for its technical moves. Use Confusion or Disable as a diversion, then land a Shadow Ball! For its Final Smash, Mewtwo transforms into Mega Mewtwo Y and fires a projectile that freezes and launches the opponent!",
		Tier:            "D+",
		Weight:          79,
		Speed:           2.255,
		NeutralB:        "Shadow Ball",
		UpB:             "Teleport",
		SideB:           "Confusion",
		DownB:           "Disable",
		Final_Smash:     "Psystrike",
		Image_URL:       "https://ssb.wiki.gallery/images/d/de/Mewtwo_SSBU.png",
	},
	{
		Name:            "Roy",
		Series:          "Fire Emblem",
		FirstAppearance: "Super Smash Bros. Melee",
		Description:     "	Get up close and personal for major damage! Unlike Marth, Roy’s attacks are more powerful the closer you get to the base of his blade. For his Final Smash, his sword bursts into flames and sends anyone caught in the blast flying.",
		Tier:            "A",
		Weight:          95,
		Speed:           2.145,
		NeutralB:        "Flare Blade",
		UpB:             "Blazer",
		SideB:           "Double-Edge Dance",
		DownB:           "Counter",
		Final_Smash:     "Critical Hit",
		Image_URL:       "https://www.ssbwiki.com/images/9/9d/Roy_SSBU.png",
	},
	{
		Name:            "Mr. Game & Watch",
		Series:          "Game & Watch",
		FirstAppearance: "Ball",
		Description:     "Now his attacks mimic the animations from his original appearance. For his side special, Judge, he pulls out a hammer and numbers 1-9 are displayed. If you pull off a 9 attack, it will really knock the opponent back. His Final Smash turns him into an octopus that can pull opponents off the stage!",
		Tier:            "S",
		Weight:          75,
		Speed:           1.679,
		NeutralB:        "Chef",
		UpB:             "Fire",
		SideB:           "Judge",
		DownB:           "Oil Panic",
		Final_Smash:     "Octopus",
		Image_URL:       "https://www.ssbwiki.com/images/c/cb/Mr._Game_%26_Watch_SSBU.png",
	},
	{
		Name:            "Meta Knight",
		Series:          "Kirby",
		FirstAppearance: "Kirby's Adventure",
		Description:     "This fighter not only has tons of quick moves, he can perform a midair jump five times! All his special moves have a recovery aspect, so use them at the right time. His Final Smash is Darkness Illusion, which unleashes a fast series of aerial attacks.",
		Tier:            "B-",
		Weight:          80,
		Speed:           2.09,
		NeutralB:        "Mach Tornado",
		UpB:             "Shuttle Loop",
		SideB:           "Drill Rush",
		DownB:           "Dimensional Cape",
		Final_Smash:     "Darkness Illusion",
		Image_URL:       "https://www.ssbwiki.com/images/0/00/Meta_Knight_SSBU.png",
	},
	{
		Name:            "Pit",
		Series:          "Kid Icarus",
		FirstAppearance: "Kid Icarus",
		Description:     "	Pit is a well-balanced, well-rounded character with a defensive special that nullifies long distance attacks and excellent recovery. He's a great choice for new players!",
		Tier:            "B-",
		Weight:          96,
		Speed:           1.828,
		NeutralB:        "Palutena Bow",
		UpB:             "Power of Flight",
		SideB:           "Upperdash Arm",
		DownB:           "Guardian Orbitars",
		Final_Smash:     "Lightning Chariot",
		Image_URL:       "https://www.ssbwiki.com/images/3/38/Pit_SSBU.png",
	},
	{
		Name:            "Dark Pit",
		Series:          "Kid Icarus",
		FirstAppearance: "Kid Icarus: Uprising",
		Description:     "Dark Pit is Pit's echo fighter. His abilities are mostly the same as Pit's, but his hair and clothes are different colors, he summons different weapons, and celebrates victory to a different tune.",
		Tier:            "B-",
		Weight:          96,
		Speed:           1.828,
		NeutralB:        "Silver Bow",
		UpB:             "Power of Flight",
		SideB:           "Electroshock Arm",
		DownB:           "Guardian Orbitars",
		Final_Smash:     "Dark Pit Staff",
		Image_URL:       "https://ssb.wiki.gallery/images/0/09/Dark_Pit_SSBU.png",
	},
	{
		Name:            "Zero Suit Samus",
		Series:          "Metroid",
		FirstAppearance: "Metroid: Zero Mission",
		Description:     "Although not as powerful as Samus, her speed is exceptional! Her Paralyzer not only has the ability to stun opponents, but it can also turn into a whip. For her Final Smash, she dons her suit and fires a powerful laser!",
		Tier:            "A-",
		Weight:          80,
		Speed:           2.31,
		NeutralB:        "Paralyzer",
		UpB:             "Boost Kick",
		SideB:           "Plasma Whip",
		DownB:           "Flip Jump",
		Final_Smash:     "Zero Laser",
		Image_URL:       "https://www.ssbwiki.com/images/f/f0/Zero_Suit_Samus_SSBU.png",
	},
	{
		Name:            "Wario",
		Series:          "Wario",
		FirstAppearance: "Super Mario Land 2: 6 Golden Coins",
		Description:     "Wario has unique attacks, like using his Wario Bike and releasing noxious gas. He can jump higher than normal by leaping from his bike, which comes in handy when recovering. For his Final Smash, he turns into Wario-Man and creates copies of himself for an all-out attack!",
		Tier:            "A",
		Weight:          107,
		Speed:           1.65,
		NeutralB:        "Chomp",
		UpB:             "Corkscrew",
		SideB:           "Wario Bike",
		DownB:           "Wario Waft",
		Final_Smash:     "Wario-Man",
		Image_URL:       "https://www.ssbwiki.com/images/0/04/Wario_SSBU.png",
	},
	{
		Name:            "Snake",
		Series:          "Metal Gear Solid",
		FirstAppearance: "Metal Gear",
		Description:     "Back by popular demand, Snake brings a ranged fighting style unlike any other fighter in the game. His Final Smash locks onto an opponent and fires five missiles.",
		Tier:            "S",
		Weight:          106,
		Speed:           1.595,
		NeutralB:        "Hand Grenade",
		UpB:             "Cypher",
		SideB:           "Remote Missile",
		DownB:           "C4",
		Final_Smash:     "Covering Fire",
		Image_URL:       "https://www.ssbwiki.com/images/0/02/Snake_SSBU.png",
	},
	{
		Name:            "Ike",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem: Path of Radiance",
		Description:     "Ike's side smash attack is extremely powerful, but it leaves him open, so you'll need to reach your opponent's moves carefully. You can choose between his Path of Radiance and Radiant Dawn costumes.",
		Tier:            "D-",
		Weight:          107,
		Speed:           1.507,
		NeutralB:        "Eruption",
		UpB:             "Aether",
		SideB:           "Quick Draw",
		DownB:           "Counter",
		Final_Smash:     "Great Aether",
		Image_URL:       "https://ssb.wiki.gallery/images/8/86/Ike_SSBU.png",
	},
	{
		Name:            "Squirtle (Pokémon Trainer)",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "At the start of their Pokémon adventures, many aspiring trainers visit Professor Oak to choose one of three starter Pokémon. Squirtle's always a popular choice, what with him being so flipping adorable. When it's in danger, though, it withdraws into its shell and spits a high-pressure burst of water, which isn't quite so adorable.",
		Tier:            "A-",
		Weight:          75,
		Speed:           1.76,
		NeutralB:        "Water Gun",
		UpB:             "Waterfall",
		SideB:           "Withdraw",
		DownB:           "Pokémon Change",
		Final_Smash:     "Triple Finish",
		Image_URL:       "https://ssb.wiki.gallery/images/7/79/Squirtle_SSBU.png",
	},
	{
		Name:            "Ivysaur (Pokémon Trainer)",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "Watching your starter Pokémon evolve is an unforgettable experience. For many trainers, that first happens when watching Bulbasaur become Ivysaur. It might be difficult for them to say goodbye to cute little Bulbasaur, but before they know it, they'll be saying bye to Ivysaur, too, when it turns into a fully-grown Venusaur!",
		Tier:            "A-",
		Weight:          96,
		Speed:           1.595,
		NeutralB:        "Bullet Seed",
		UpB:             "Vine Whip",
		SideB:           "Razor Leaf",
		DownB:           "Pokémon Change",
		Final_Smash:     "Triple Finish",
		Image_URL:       "https://ssb.wiki.gallery/images/5/52/Ivysaur_SSBU.png",
	},
	{
		Name:            "Charizard (Pokémon Trainer)",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Red and Green",
		Description:     "The iconic Fire/Flying-type Pokémon. Charizard's scorching breath can melt anything in its path. It soars through the air, seeking only worthy foes to test itself against. In Smash Bros., Charizard unleashes the destructive Flare Blitz special move— a move so strong, it even injures the user!",
		Tier:            "A-",
		Weight:          116,
		Speed:           2.2,
		NeutralB:        "Flamethrower",
		UpB:             "Fly",
		SideB:           "Flare Blitz",
		DownB:           "Pokémon Change",
		Final_Smash:     "Triple Finish",
		Image_URL:       "https://www.ssbwiki.com/images/2/21/Charizard_SSBU.png",
	},
	{
		Name:            "Diddy Kong",
		Series:          "Donkey Kong",
		FirstAppearance: "Donkey Kong Country",
		Description:     "Donkey Kong’s trusty partner Diddy Kong uses his light weight and agility to get around quickly! For his Final Smash, Diddy takes to the air with his Rocketbarrel while firing his popguns. The final hit is seriously powerful!",
		Tier:            "S-",
		Weight:          90,
		Speed:           2.006,
		NeutralB:        "Peanut Popgun",
		UpB:             "Rocketbarrel Boost",
		SideB:           "Monkey Flip",
		DownB:           "Banana Peel",
		Final_Smash:     "Hyper Rocketbarrel",
		Image_URL:       "https://ssb.wiki.gallery/images/a/a7/Diddy_Kong_SSBU.png",
	},
	{
		Name:            "Lucas",
		Series:          "Earthbound",
		FirstAppearance: "Mother 3",
		Description:     "Like Ness, Lucas is a young boy who uses PSI powers. Some of their PSI moves share the same names, but since Lucas has different abilities, the moves may work differently. Be sure to try them out! For his Final Smash, he calls down a shower of meteors along with Kumatora and Boney.",
		Tier:            "C-",
		Weight:          94,
		Speed:           1.65,
		NeutralB:        "PK Freeze",
		UpB:             "PK Thunder",
		SideB:           "PK Fire",
		DownB:           "PSI Magnet",
		Final_Smash:     "PK Starstorm",
		Image_URL:       "https://ssb.wiki.gallery/images/8/81/Lucas_SSBU.png",
	},
	{
		Name:            "Sonic",
		Series:          "Sonic the Hedgehog",
		FirstAppearance: "Rad Mobile",
		Description:     "This speedy fighter has a lot of rush-type attacks. His Final Smash, Super Sonic, let's him fly around the stage at an incredible speed!",
		Tier:            "S+",
		Weight:          86,
		Speed:           3.85,
		NeutralB:        "Homing Attack",
		UpB:             "Spring Jump",
		SideB:           "Spin Dash",
		DownB:           "Spin Charge",
		Final_Smash:     "Super Sonic",
		Image_URL:       "https://ssb.wiki.gallery/images/b/ba/Sonic_SSBU.png",
	},
	{
		Name:            "King Dedede",
		Series:          "Kirby",
		FirstAppearance: "Kirby's Dream Land",
		Description:     "He's not very fast, but he's one of few heavyweight fighters with great recovery. Apparently, his first defeat by Kirby inspired him to train hard to learn a move called Hovering, which allows him to float after taking a deep breath.",
		Tier:            "E+",
		Weight:          127,
		Speed:           1.496,
		NeutralB:        "Inhale",
		UpB:             "Super Dedede Jump",
		SideB:           "Gordo Throw",
		DownB:           "Jet Hammer",
		Final_Smash:     "Dede-Rush",
		Image_URL:       "https://ssb.wiki.gallery/images/f/f5/King_Dedede_SSBU.png",
	},
	{
		Name:            "Olimar",
		Series:          "Pikmin",
		FirstAppearance: "Pikmin",
		Description:     "Captain Olimar battles by issuing commands to various types of Pikmin under his control. Pikmin comes in different colors that correspond to different abilities. Olimar’s alternate appearance lets you play as Alph!",
		Tier:            "B+",
		Weight:          79,
		Speed:           1.617,
		NeutralB:        "Pikmin Pluck",
		UpB:             "Winged Pikmin",
		SideB:           "Pikmin Throw",
		DownB:           "Pikmin Order",
		Final_Smash:     "End of Day",
		Image_URL:       "https://www.ssbwiki.com/images/b/b3/Olimar_SSBU.png",
	},
	{
		Name:            "Lucario",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Diamond and Pearl",
		Description:     "Lucario is the only fighter whose attack power increases as it takes damage. A fighter that truly shines when in a pinch, choose Lucario for a thrilling battle.",
		Tier:            "C+",
		Weight:          92,
		Speed:           1.705,
		NeutralB:        "Aura Sphere",
		UpB:             "Extreme Speed",
		SideB:           "Force Palm",
		DownB:           "Double Team",
		Final_Smash:     "Aura Storm",
		Image_URL:       "https://ssb.wiki.gallery/images/0/08/Lucario_SSBU.png",
	},
	{
		Name:            "R.O.B.",
		Series:          "R.O.B.",
		FirstAppearance: "Stack-Up",
		Description:     "He has two powerful projectiles: Robo Beam and Gyro, along with a very effective recovery. The 1P color in the North American version of the game is a light gray, and the 2P is red and white, but this is reversed in the Japanese version.",
		Tier:            "S",
		Weight:          106,
		Speed:           1.725,
		NeutralB:        "Robo Beam",
		UpB:             "Robo Burner",
		SideB:           "Arm Rotor",
		DownB:           "Gyro",
		Final_Smash:     "Guided Robo Beam",
		Image_URL:       "https://ssb.wiki.gallery/images/3/38/R.O.B._%28JPN%29_SSBU.png",
	},
	{
		Name:            "Toon Link",
		Series:          "The Legend of Zelda",
		FirstAppearance: "The Legend of Zelda: The Wind Waker",
		Description:     "	He's smaller and faster than Link. His bombs explode with a unique anime-style. For his Final Smash, he emits light from his left hand and any opponents hit by it are trapped in the Triforce, subject to a punishing gauntlet of attacks.",
		Tier:            "B-",
		Weight:          91,
		Speed:           1.906,
		NeutralB:        "Hero's Bow",
		UpB:             "Spin Attack",
		SideB:           "Boomerang",
		DownB:           "Bomb",
		Final_Smash:     "Triforce Slash",
		Image_URL:       "https://ssb.wiki.gallery/images/5/56/Toon_Link_SSBU.png",
	},
	{
		Name:            "Wolf",
		Series:          "Star Fox",
		FirstAppearance: "Star Fox 64",
		Description:     "The leader of the Star Wolf mercenary team makes his grand return after 10 years! He puts his sharp claws to good use in wild attacks, and his Final Smash is an all-out attack by Team Star Wolf! If Fox or Falco is in the battle, you may hear a unique line of dialog.",
		Tier:            "A",
		Weight:          92,
		Speed:           1.54,
		NeutralB:        "Blaster",
		UpB:             "Fire Wolf",
		SideB:           "Wolf Flash",
		DownB:           "Reflector",
		Final_Smash:     "Team Star Wolf",
		Image_URL:       "https://ssb.wiki.gallery/images/8/8a/Wolf_SSBU.png",
	},
	{
		Name:            "Villager",
		Series:          "Animal Crossing",
		FirstAppearance: "Animal Crossing",
		Description:     "This fighter attacks using skills from daily life in the village, such as planting, growing, and cutting down trees. They can also use items like nets, slingshots, and turnips. The Villager can also put items or incoming projectiles in a pocket to use later.",
		Tier:            "D-",
		Weight:          92,
		Speed:           1.397,
		NeutralB:        "Pocket",
		UpB:             "Balloon Trip",
		SideB:           "Lloid Rocket",
		DownB:           "Timber",
		Final_Smash:     "Dream Home",
		Image_URL:       "https://www.ssbwiki.com/images/a/ac/Villager_SSBU.png",
	},
	{
		Name:            "Mega Man",
		Series:          "Mega Man",
		FirstAppearance: "Mega Man",
		Description:     "Mega Man's standard and special moves use weapons copied from the bosses he's fought throughout the Mega Man series, so he has more projectiles than any other fighter. His Final Smash now features Proto Man and Bass!",
		Tier:            "B-",
		Weight:          102,
		Speed:           1.602,
		NeutralB:        "Metal Blade",
		UpB:             "Rush Coil",
		SideB:           "Crash Bomber",
		DownB:           "Leaf Shield",
		Final_Smash:     "Mega Legends",
		Image_URL:       "https://ssb.wiki.gallery/images/4/46/Mega_Man_SSBU.png",
	},
	{
		Name:            "Wii Fit Trainer",
		Series:          "Wii Fit",
		FirstAppearance: "Wii Fit",
		Description:     "A fighter that attacks with healthy moves like stretching and yoga poses. You can pick between male and female versions. Charging up Sun Salutation all the way recovers a bit of health!",
		Tier:            "C-",
		Weight:          96,
		Speed:           1.866,
		NeutralB:        "Sun Salutation",
		UpB:             "Super Hoop",
		SideB:           "Header",
		DownB:           "Deep Breathing",
		Final_Smash:     "Wii Fit",
		Image_URL:       "https://ssb.wiki.gallery/images/f/ff/Wii_Fit_Trainer_SSBU.png",
	},
	{
		Name:            "Rosalina & Luma",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Galaxy",
		Description:     "	Luma mimics Rosalina’s attacks. Luma also increases Rosalina’s reach and can even take a hit for her! If Rosalina gets hit, Luma gets very flustered and flutters both hands.",
		Tier:            "B-",
		Weight:          82,
		Speed:           1.795,
		NeutralB:        "Luma Shot",
		UpB:             "Launch Star",
		SideB:           "Star Bits",
		DownB:           "Gravitational Pull",
		Final_Smash:     "Grand Star",
		Image_URL:       "https://ssb.wiki.gallery/images/1/16/Rosalina_%26_Luma_SSBU.png",
	},
	{
		Name:            "Little Mac",
		Series:          "Punch-Out!!",
		FirstAppearance: "Punch-Out!!",
		Description:     "As a boxer, Little Mac fights with his fists alone—no kicks! When his Power Meter fills up, he can use a special KO Uppercut, which can really turn a battle around. For his Final Smash, he turns into Giga Mac and pummels the opponent with a furious rush of punches!",
		Tier:            "E+",
		Weight:          87,
		Speed:           2.464,
		NeutralB:        "Straight Lunge",
		UpB:             "Rising Uppercut",
		SideB:           "Jolt Haymaker",
		DownB:           "Slip Counter",
		Final_Smash:     "Giga Mac Rush",
		Image_URL:       "https://www.ssbwiki.com/images/5/53/Little_Mac_SSBU.png",
	},
	{
		Name:            "Greninja",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon X and Y",
		Description:     "A ninja-like fighter that battles with moves like the Water Shuriken. Greninja can use a log for clever counterattacks, and this Pokémon can even stick to walls. During its Final Smash, it turns into Ash-Greninja...?!",
		Tier:            "B+",
		Weight:          88,
		Speed:           2.288,
		NeutralB:        "Water Shuriken",
		UpB:             "Hydro Pump",
		SideB:           "Shadow Sneak",
		DownB:           "Substitute",
		Final_Smash:     "Secret Ninja Attack",
		Image_URL:       "https://ssb.wiki.gallery/images/d/da/Greninja_SSBU.png",
	},
	{
		Name:            "Mii Brawler",
		Series:          "Super Smash Bros.",
		FirstAppearance: "Mii Channel",
		Description:     "You can choose from the three types of Mii Fighter and select from a set of three specials for each type. You can also choose one of 12 voice options!",
		Tier:            "B+",
		Weight:          94,
		Speed:           1.92,
		NeutralB:        "Shot Put",
		UpB:             "Soaring Axe Kick",
		SideB:           "Onslaught",
		DownB:           "Head-On Assault",
		Final_Smash:     "Omega Blitz",
		Image_URL:       "https://ssb.wiki.gallery/images/e/e4/Mii_Brawler_SSBU.png",
	},
	{
		Name:            "Mii Swordfighter",
		Series:          "Super Smash Bros.",
		FirstAppearance: "Mii Channel",
		Description:     "You can choose from the three types of Mii Fighter and select from a set of three specials for each type. You can also choose one of 12 voice options!",
		Tier:            "B+",
		Weight:          100,
		Speed:           1.58,
		NeutralB:        "Gale Strike",
		UpB:             "Stone Scabbard",
		SideB:           "Airborne Assault",
		DownB:           "Blade Counter",
		Final_Smash:     "Final Edge",
		Image_URL:       "https://ssb.wiki.gallery/images/f/fa/Mii_Swordfighter_SSBU.png",
	},
	{
		Name:            "Mii Gunner",
		Series:          "Super Smash Bros.",
		FirstAppearance: "Mii Channel",
		Description:     "You can choose from the three types of Mii Fighter and select from a set of three specials for each type. You can also choose one of 12 voice options!",
		Tier:            "B+",
		Weight:          104,
		Speed:           1.37,
		NeutralB:        "	Charge Blast",
		UpB:             "Lunar Launch",
		SideB:           "Flame Pillar",
		DownB:           "Echo Reflector",
		Final_Smash:     "Full Blast",
		Image_URL:       "https://ssb.wiki.gallery/images/e/e5/Mii_Gunner_SSBU.png",
	},
	{
		Name:            "Palutena",
		Series:          "Kid Icarus",
		FirstAppearance: "Kid Icarus",
		Description:     "With her wings and staff, this goddess's attacks cover a wide range. With her up smash, neutral special and side special, she can create a ranged attack in almost every direction except for directly beneath her! Keep the pressure on your opponents from a distance with ranged attacks!",
		Tier:            "A",
		Weight:          91,
		Speed:           2.077,
		NeutralB:        "Autoreticle",
		UpB:             "Warp",
		SideB:           "Explosive Flame",
		DownB:           "Counter/Reflect Barrier",
		Final_Smash:     "Black Hole Laser",
		Image_URL:       "https://www.ssbwiki.com/images/6/6b/Palutena_SSBU.png",
	},
	{
		Name:            "Pac-Man",
		Series:          "Pac-Man",
		FirstAppearance: "Pac-Man",
		Description:     "This fighter appears in both his classic form and his form with hands and legs. He has many unique special moves, such as using a trampoline or a fire hydrant. For his Final Smash, he grows into a giant Super PAC-MAN, chomping and launching his opponents!",
		Tier:            "A",
		Weight:          95,
		Speed:           1.672,
		NeutralB:        "Bonus Fruit",
		UpB:             "Pac-Jump",
		SideB:           "Power Pellet",
		DownB:           "Fire Hydrant",
		Final_Smash:     "Super Pac-Man",
		Image_URL:       "https://www.ssbwiki.com/images/0/03/Pac-Man_SSBU.png",
	},
	{
		Name:            "Robin",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem Awakening",
		Description:     "A fighter that wields the Levin Sword and four different Tomes! Like in the original game, these weapons can only be used a certain number of times, so keep a close eye on the battle situation. Both the male and female versions of Robin are available, so you can choose your favorite.",
		Tier:            "D+",
		Weight:          95,
		Speed:           1.265,
		NeutralB:        "Thunder",
		UpB:             "Elwind",
		SideB:           "Arcfire",
		DownB:           "Nosferatu",
		Final_Smash:     "Pair Up",
		Image_URL:       "https://www.ssbwiki.com/images/8/82/Robin_SSBU.png",
	},
	{
		Name:            "Shulk",
		Series:          "Xenoblade Chronicles",
		FirstAppearance: "Xenoblade Chronicles",
		Description:     "He is the only fighter that can change his status during battle. His sword, the Monado, allows him to switch between five modes—Jump, Speed, Shield, Buster and Smash—which change his abilities for a short time. Fun fact: Shulk’s eighth color variation puts him in a pair of swimming trunks!",
		Tier:            "A-",
		Weight:          97,
		Speed:           1.672,
		NeutralB:        "Monado Arts",
		UpB:             "Air Slash",
		SideB:           "Back Slash",
		DownB:           "Vision",
		Final_Smash:     "Chain Attack",
		Image_URL:       "https://ssb.wiki.gallery/images/0/0f/Shulk_SSBU.png",
	},
	{
		Name:            "Bowser Jr.",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Sunshine",
		Description:     "The Jr. Clown Car this little fella rides in takes less damage when attacked than Bowser Jr. himself—so try to stay in the car when taking damage. The different color variations are the Koopalings!",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://ssb.wiki.gallery/images/2/2b/Bowser_Jr._SSBU.png",
	},
	{
		Name:            "Duck Hunt",
		Series:          "Duck Hunt",
		FirstAppearance: "Duck Hunt",
		Description:     "	This duo excels at long-range attacks, like kicking exploding cans and throwing clay pigeons. For their Final Smash, three games from the Light Gun Series team up: Duck Hunt, Hogan's Alley, and Wild Gunman!",
		Tier:            "C-",
		Weight:          86,
		Speed:           1.793,
		NeutralB:        "Trick Shot",
		UpB:             "Duck Jump",
		SideB:           "Clay Shooting",
		DownB:           "Wild Gunman",
		Final_Smash:     "NES Zapper Posse",
		Image_URL:       "https://ssb.wiki.gallery/images/d/d8/Duck_Hunt_SSBU.png",
	},
	{
		Name:            "Ryu",
		Series:          "Street Fighter",
		FirstAppearance: "Street Fighter",
		Description:     "Ryu is a special character—you can use directional command inputs to trigger his special moves. Executing moves like his Hadoken and Shoryuken using the command inputs from the original game will raise their power. You can even use a Shakunetsu Hadoken by inputting ←↙↓↘→ then tapping the attack button while facing right!",
		Tier:            "B+",
		Weight:          103,
		Speed:           1.6,
		NeutralB:        "Hadoken",
		UpB:             "Shoryuken",
		SideB:           "Tatsumaki Senpukyaku",
		DownB:           "Focus Attack",
		Final_Smash:     "Shin Shoryuken / Shinku Hadoken",
		Image_URL:       "https://ssb.wiki.gallery/images/6/61/Ryu_SSBU.png",
	},
	{
		Name:            "Cloud",
		Series:          "Final Fantasy",
		FirstAppearance: "Final Fantasy VII",
		Description:     "He's the protagonist of Final Fantasy VII. You can also select his Advent Children outfit. Charging up his Limit Gauge increases his special move abilities! Land a powerful hit!",
		Tier:            "A+",
		Weight:          100,
		Speed:           2.167,
		NeutralB:        "Blade Beam",
		UpB:             "Climhazzard",
		SideB:           "Cross Slash",
		DownB:           "Limit Charge / Finishing Touch",
		Final_Smash:     "Omnislash / Omnislash Ver. 5",
		Image_URL:       "https://ssb.wiki.gallery/images/b/b3/Cloud_SSBU.png",
	},
	{
		Name:            "Corrin",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem Fates",
		Description:     "Corrin was available as a downloadable fighter in the previous version of Super Smash Bros. This fighter uses all kinds of attacks, like Torrential Roar and Dragon Fang Shot. Players can choose male or female versions!",
		Tier:            "A-",
		Weight:          98,
		Speed:           1.595,
		NeutralB:        "Dragon Fang Shot",
		UpB:             "Dragon Ascent",
		SideB:           "Dragon Lunge",
		DownB:           "Counter Surge",
		Final_Smash:     "Torrential Roar",
		Image_URL:       "https://ssb.wiki.gallery/images/c/c4/Corrin_SSBU.png",
	},
	{
		Name:            "Bayonetta",
		Series:          "Bayonetta",
		FirstAppearance: "Bayonetta",
		Description:     "An Umbra Witch who equips guns on her arms and legs, Bayonetta has mastered the beautiful but brutal Bullet Arts fighting style. She can even slow down her opponents with Witch Time!",
		Tier:            "A-",
		Weight:          81,
		Speed:           1.76,
		NeutralB:        "Bullet Climax",
		UpB:             "Witch Twist",
		SideB:           "Heel Slide / After Burner Kick",
		DownB:           "Witch Time",
		Final_Smash:     "Infernal Climax",
		Image_URL:       "https://www.ssbwiki.com/images/7/7c/Bayonetta_SSBU.png",
	},
	{
		Name:            "Dark Samus",
		Series:          "Metroid",
		FirstAppearance: "Metroid Prime",
		Description:     "Dark Samus joins the battle as Samus's echo fighter. With floatier movement, it's a little different from Samus--and it doesn't roll when dodging or jumping. If you look closely, you can see that its bombs and missiles look a little different, too.",
		Tier:            "A",
		Weight:          108,
		Speed:           1.654,
		NeutralB:        "Charge Shot",
		UpB:             "Screw Attack",
		SideB:           "Missile",
		DownB:           "Bomb",
		Final_Smash:     "Phazon Laser",
		Image_URL:       "https://ssb.wiki.gallery/images/a/a6/Dark_Samus_SSBU.png",
	},
	{
		Name:            "Daisy",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Land",
		Description:     "Her basic move set is the same as Peach's, but this princess has her own unique personality. She's known for being upbeat, energetic, and a bit of a tomboy.",
		Tier:            "S-",
		Weight:          89,
		Speed:           1.595,
		NeutralB:        "Toad",
		UpB:             "Daisy Parasol",
		SideB:           "Daisy Bomber",
		DownB:           "Vegetable",
		Final_Smash:     "Daisy Blossom",
		Image_URL:       "https://ssb.wiki.gallery/images/2/21/Daisy_SSBU.png",
	},
	{
		Name:            "Chrom",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem Awakening",
		Description:     "The protagonist of Fire Emblem Awakening joins the battle as Roy's echo fighter. His final smash is Awakening Aether. Like Aether in the original game, this move has Chrom charge toward his opponent, slashing with his sword.",
		Tier:            "C+",
		Weight:          95,
		Speed:           2.145,
		NeutralB:        "Flare Blade",
		UpB:             "Soaring Slash",
		SideB:           "Double-Edge Dance",
		DownB:           "Counter",
		Final_Smash:     "Awakening Aether",
		Image_URL:       "https://www.ssbwiki.com/images/5/57/Chrom_SSBU.png",
	},
	{
		Name:            "Ken",
		Series:          "Street Fighter",
		FirstAppearance: "Street Fighter",
		Description:     "	Ken joins the battle as Ryu’s Echo Fighter! Their differences are carried over from the original game: Ken’s Hadoken is shaped differently, his strong Shoryuken has flames, and he moves a bit faster. He has two final smashes: Shinryuken and Shippu Jinraikyaku.",
		Tier:            "B-",
		Weight:          103,
		Speed:           1.76,
		NeutralB:        "Hadoken",
		UpB:             "Shoryuken",
		SideB:           "Tatsumaki Senpukyaku",
		DownB:           "Focus Attack",
		Final_Smash:     "Shippu Jinraikyaku / Shinryuken",
		Image_URL:       "https://ssb.wiki.gallery/images/f/f6/Ken_SSBU.png",
	},
	{
		Name:            "Inkling",
		Series:          "Splatoon",
		FirstAppearance: "Splatoon",
		Description:     "	Attacks with a variety of weapons. Covering opponents with ink leads to more and more damage–plus these Inklings are really fashionable!",
		Tier:            "B-",
		Weight:          94,
		Speed:           1.925,
		NeutralB:        "Splattershot",
		UpB:             "Super Jump",
		SideB:           "Splat Roller",
		DownB:           "Splat Bomb",
		Final_Smash:     "Killer Wail",
		Image_URL:       "https://ssb.wiki.gallery/images/2/2e/Inkling_SSBU.png",
	},
	{
		Name:            "Ridley",
		Series:          "Metroid",
		FirstAppearance: "Metroid",
		Description:     "Joining the battle from the storied Metroid series, Ridley's long tail and sharp claws let him unleash a torrent of devastating attacks. His Final Smash is a powerful stream of plasma breath intense enough to bring down Samus's starship.",
		Tier:            "C-",
		Weight:          107,
		Speed:           2.2,
		NeutralB:        "Plasma Breath",
		UpB:             "Wing Blitz",
		SideB:           "Space Pirate Rush",
		DownB:           "Skewer",
		Final_Smash:     "Plasma Scream",
		Image_URL:       "https://www.ssbwiki.com/images/2/27/Ridley_SSBU.png",
	},
	{
		Name:            "Simon",
		Series:          "Castlevania",
		FirstAppearance: "Castlevania",
		Description:     "he protagonist of Castlevania. He uses his holy whip, Vampire Killer, to perform a smash attack with long reach. He also uses projectiles like an Axe, Holy Water, and Cross.",
		Tier:            "D-",
		Weight:          107,
		Speed:           1.52,
		NeutralB:        "Axe",
		UpB:             "Uppercut",
		SideB:           "Cross",
		DownB:           "Holy Water",
		Final_Smash:     "Grand Cross",
		Image_URL:       "https://www.ssbwiki.com/images/9/95/Simon_SSBU.png",
	},
	{
		Name:            "Richter",
		Series:          "Castlevania",
		FirstAppearance: "Castlevania: Rondo of Blood",
		Description:     "Richter from the Castlevania series joins the battle as Simon's echo fighter! His basic attacks are the same as Simon's, but with subtle variations. In addition to that, his holy water is a different color.",
		Tier:            "D-",
		Weight:          107,
		Speed:           1.52,
		NeutralB:        "Axe",
		UpB:             "Uppercut",
		SideB:           "Cross",
		DownB:           "Holy Water",
		Final_Smash:     "Grand Cross",
		Image_URL:       "https://www.ssbwiki.com/images/c/c2/Richter_SSBU.png",
	},
	{
		Name:            "King K. Rool",
		Series:          "Donkey Kong",
		FirstAppearance: "Donkey Kong Country",
		Description:     "With long-distance special moves like the Blunderbuss, and counter moves like Stomach Attack, he is a versatile fighter. His Final Smash, Blast-O-Matic, was apparently a weapon created to destroy DK Island...",
		Tier:            "E+",
		Weight:          133,
		Speed:           1.485,
		NeutralB:        "Blunderbuss",
		UpB:             "Propellerpack",
		SideB:           "Crownerang",
		DownB:           "Gut Check",
		Final_Smash:     "Blast-O-Matic",
		Image_URL:       "https://www.ssbwiki.com/images/b/b6/King_K._Rool_SSBU.png",
	},
	{
		Name:            "Isabelle",
		Series:          "Animal Crossing",
		FirstAppearance: "Animal Crossing: New Leaf",
		Description:     `Isabelle joins the battle from Animal Crossing: New Leaf! She uses various trinkets from around the village to battle. Her side special, ""Fishing Rod,"" not only allows her to snag and bring opponents closer, it can also be used as a recovery move.`,
		Tier:            "D+",
		Weight:          88,
		Speed:           1.48,
		NeutralB:        "Pocket",
		UpB:             "Balloon Trip",
		SideB:           "Fishing Rod",
		DownB:           "Lloid Trap",
		Final_Smash:     "Dream Town Hall",
		Image_URL:       "https://www.ssbwiki.com/images/2/2b/Isabelle_SSBU.png",
	},
	{
		Name:            "Incineroar",
		Series:          "Pokémon",
		FirstAppearance: "Pokémon Sun and Moon",
		Description:     "A fighter with many special moves that appear to come from the world of pro wrestling. Incineroar has many moves from its original game, like Darkest Lariat, Cross Chop, and Revenge. Its Final Smash is Max Malicious Moonsault. Let the Z power explode and deliver a powerful blow!",
		Tier:            "C+",
		Weight:          116,
		Speed:           1.18,
		NeutralB:        "Darkest Lariat",
		UpB:             "Cross Chop",
		SideB:           "Alolan Whip",
		DownB:           "Revenge",
		Final_Smash:     "Max Malicious Moonsault",
		Image_URL:       "https://ssb.wiki.gallery/images/c/c4/Incineroar_SSBU.png",
	},
	{
		Name:            "Piranha Plant",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros.",
		Description:     "Piranha Plant is a very unique fighter, as he's tied to the large pot that the plant comes from - but can still hobble about the stage. Despite his size, the length of his stalk can expand rapidly for some surprising reach attacks.",
		Tier:            "D-",
		Weight:          112,
		Speed:           1.72,
		NeutralB:        "Ptooie",
		UpB:             "Piranhacopter",
		SideB:           "Poison Breath",
		DownB:           "Long-Stem Strike",
		Final_Smash:     "Petey Piranha",
		Image_URL:       "https://ssb.wiki.gallery/images/f/f0/Piranha_Plant_SSBU.png",
	},
	{
		Name:            "Joker",
		Series:          "Persona",
		FirstAppearance: "Persona 5",
		Description:     "Joker steals the show when he joins the Super Smash Bros. Ultimate game as a playable fighter! This speedy fighter wields a knife and a gun to rack up damage. When his Rebellion Gauge is full, Joker summons his Persona, Arsene, to immediately power up his attacks for a limited time. This pack also includes Mementos, a stage that changes colors, depending on which music track is playing!",
		Tier:            "S-",
		Weight:          93,
		Speed:           2.06,
		NeutralB:        "Gun / Gun Special",
		UpB:             "Grappling Hook / Wings of Rebellion",
		SideB:           "Eiha / Eigaon",
		DownB:           "Rebel's Guard / Tetrakarn / Makarakarn",
		Final_Smash:     "All-Out Attack",
		Image_URL:       "https://www.ssbwiki.com/images/6/64/Joker_and_Arsene_SSBU.png",
	},
	{
		Name:            "Hero (Luminary)",
		Series:          "Dragon Quest",
		FirstAppearance: "Dragon Quest XI",
		Description:     "The Hero of Dragon Quest XI, known as the Luminary within his story, is a young man from the sleepy village of Cobblestone. After participating in a coming-of-age ceremony, he finds out he is the reincarnation of an ancient Hero who once saved the world. On his 16th birthday, he sets out on his journey in order to fulfill his destiny.",
		Tier:            "B-",
		Weight:          101,
		Speed:           1.84,
		NeutralB:        "Frizz / Frizzle / Kafrizz",
		UpB:             "Woosh / Swoosh / Kaswoosh",
		SideB:           "Zap / Zapple / Kazap",
		DownB:           "Command Selection",
		Final_Smash:     "Gigaslash",
		Image_URL:       "https://www.ssbwiki.com/images/0/07/Hero_SSBU.png",
	},
	{
		Name:            "Banjo & Kazooie",
		Series:          "Banjo-Kazooie",
		FirstAppearance: "Diddy Kong Racing",
		Description:     "Banjo and Kazooie must be respected by opponents since they can bully their way through just about anything, effectively nullify certain edge guarding tactics by being completely invulnerable on their way back to the ledge, and punish those trying to keep them out with projectiles. Without a feather, they become incredibly straightforward, armed with just a slow forward-smash, a slow forward-air, and short range up and down smashes as their main kill moves.",
		Tier:            "C-",
		Weight:          106,
		Speed:           2.18,
		NeutralB:        "Egg Firing / Breegull Blaster",
		UpB:             "Shock Spring Jump",
		SideB:           "Wonderwing",
		DownB:           "Rear Egg",
		Final_Smash:     "The Mighty Jinjonator",
		Image_URL:       "https://www.ssbwiki.com/images/9/97/Banjo_%26_Kazooie_SSBU.png",
	},
	{
		Name:            "Terry",
		Series:          "Fatal Fury",
		FirstAppearance: "Fatal Fury: King of Fighters",
		Description:     "Terry is a tall, heavyweight fighter who weighs the same as Samus, Dark Samus, and Bowser Jr. Due to hailing from a traditional fighting game series, Terry always faces his opponent in 1-on-1 matches, a trait that he shares with Ryu, Ken, and Kazuya.",
		Tier:            "A-",
		Weight:          108,
		Speed:           1.72,
		NeutralB:        "Power Wave",
		UpB:             "Rising Tackle",
		SideB:           "Burning Knuckle / Crack Shoot",
		DownB:           "Power Dunk",
		Final_Smash:     "Triple Wolf",
		Image_URL:       "https://ssb.wiki.gallery/images/f/f5/Terry_SSBU.png",
	},
	{
		Name:            "Byleth",
		Series:          "Fire Emblem",
		FirstAppearance: "Fire Emblem: Three Houses",
		Description:     "From Fire Emblem: Three Houses. Using a variety of Heroes' Relics, including the Sword of the Creator, Byleth is ready to teach foes what Super Smash Bros. is all about!",
		Tier:            "B-",
		Weight:          97,
		Speed:           1.43,
		NeutralB:        "Failnaught",
		UpB:             "Sword of the Creator",
		SideB:           "Areadbhar",
		DownB:           "Aymr",
		Final_Smash:     "Progenitor God Ruptured Heaven",
		Image_URL:       "https://ssb.wiki.gallery/images/3/3d/Byleth_SSBU.png",
	},
	{
		Name:            "Min Min",
		Series:          "ARMS",
		FirstAppearance: "ARMS",
		Description:     "Min Min's ARMS give her a unique control scheme: the A button and B button control her left and right ARMS, respectively; by extension, they result in her special moveset technically consisting of only an up special move (ARMS Jump / ARM Hook) and a down special move (ARMS Change).",
		Tier:            "A+",
		Weight:          104,
		Speed:           1.55,
		NeutralB:        "Punch",
		UpB:             "ARMS Jump / ARM Hook",
		SideB:           "Punch",
		DownB:           "ARMS Change",
		Final_Smash:     "ARMS Rush",
		Image_URL:       "https://ssb.wiki.gallery/images/3/35/Min_Min_SSBU.png",
	},
	{
		Name:            "Steve",
		Series:          "Minecraft",
		FirstAppearance: "Minecraft",
		Description:     "Steve can place blocks, which crack and break automatically overtime after placing them. The only blocks he can place are dirt, oak planks, stone, iron blocks, TNT (as down special), and magma blocks (as up smash). Depending on the stage, the dirt can appear as white wool, sand (which does not fall), or ice.",
		Tier:            "S+",
		Weight:          92,
		Speed:           1.45,
		NeutralB:        "Mine / Craft / Create Block",
		UpB:             "Elytra",
		SideB:           "Minecart",
		DownB:           "TNT",
		Final_Smash:     "House of Boom",
		Image_URL:       "https://www.ssbwiki.com/images/3/3a/Steve_SSBU.png",
	},
	{
		Name:            "Sephiroth",
		Series:          "Final Fantasy",
		FirstAppearance: "Final Fantasy VII",
		Description:     "Sephiroth has a unique fighter ability called the Winged Form. While active, it increases his overall damage output by applying a multiplier of 1.3×, improves his mobility by applying multipliers to his attributes, and grants him both a third jump and damage-based armor to his smash attacks.",
		Tier:            "B+",
		Weight:          79,
		Speed:           1.86,
		NeutralB:        "Flare / Megaflare / Gigaflare",
		UpB:             "Blade Dash / Octaslash",
		SideB:           "Shadow Flare",
		DownB:           "Scintilla",
		Final_Smash:     "Supernova",
		Image_URL:       "https://www.ssbwiki.com/images/4/49/Sephiroth_SSBU.png",
	},
	{
		Name:            "Pyra",
		Series:          "Xenoblade Chronicles",
		FirstAppearance: "Xenoblade Chronicles 2 ",
		Description:     "Pyra and Mythra are the human personifications of the legendary Blade Aegis, which is used by their Driver Rex. The girls form a special bond with Rex and share a life force with him, meaning if one were to die, the other will follow suit. The pair consider themselves sisters, having the ability to mentally communicate with each other through a psychic link. They are also capable of switching into each other freely whenever the need arises.",
		Tier:            "S",
		Weight:          92,
		Speed:           1.38,
		NeutralB:        "Flame Nova",
		UpB:             "Prominence Revolt",
		SideB:           "Blazing End",
		DownB:           "Swap to Mythra",
		Final_Smash:     "Burning Sword",
		Image_URL:       "https://ssb.wiki.gallery/images/e/ec/Pyra_SSBU.png",
	},
	{
		Name:            "Mythra",
		Series:          "Xenoblade Chronicles",
		FirstAppearance: "Xenoblade Chronicles 2 ",
		Description:     "Pyra and Mythra are the human personifications of the legendary Blade Aegis, which is used by their Driver Rex. The girls form a special bond with Rex and share a life force with him, meaning if one were to die, the other will follow suit. The pair consider themselves sisters, having the ability to mentally communicate with each other through a psychic link. They are also capable of switching into each other freely whenever the need arises.",
		Tier:            "S",
		Weight:          92,
		Speed:           2.41,
		NeutralB:        "Lightning Buster",
		UpB:             "Ray of Punishment / Chroma Dust",
		SideB:           "Photon Edge",
		DownB:           "Swap to Pyra",
		Final_Smash:     "Sacred Arrow",
		Image_URL:       "https://www.ssbwiki.com/images/5/58/Mythra_SSBU.png",
	},
	{
		Name:            "Kazuya",
		Series:          "Tekken",
		FirstAppearance: "Tekken",
		Description:     "Kazuya has excellent staying power due to his heavy weight, passive armor which lets him shrug off very weak attacks, armor during his smash attacks, and a surprisingly good recovery for a heavyweight courtesy of his high double jump and Devil Wings, allowing him to make use of Rage.",
		Tier:            "A+",
		Weight:          113,
		Speed:           1.55,
		NeutralB:        "Devil Blaster",
		UpB:             "Devil Wings",
		SideB:           "Devil Fist",
		DownB:           "Heaven's Door",
		Final_Smash:     "Final Blaster",
		Image_URL:       "https://www.ssbwiki.com/images/d/d9/Kazuya_SSBU.png",
	},
	{
		Name:            "Sora",
		Series:          "Kingdom Hearts",
		FirstAppearance: "Kingdom Hearts",
		Description:     "Being a crossover between Disney and Square Enix, this tells a story of a boy named Sora who travels into various worlds related to Disney, Square Enix, and Pixar. The main heroes of this franchise often clash against multiple incarnations of Xehanort who is the main antagonist.",
		Tier:            "A",
		Weight:          85,
		Speed:           1.58,
		NeutralB:        "Magic",
		UpB:             "Aerial Sweep",
		SideB:           "Sonic Blade",
		DownB:           "Counterattack",
		Final_Smash:     "Sealing the Keyhole",
		Image_URL:       "https://www.ssbwiki.com/images/2/2d/Sora_SSBU.png",
	},
	{
		Name:            "Alph",
		Series:          "Pikmin",
		FirstAppearance: "Pikmin 3",
		Description:     "Alph is one of three explorers in Pikmin 3. He wears a spacesuit with a blue lapel, has teal-colored hair similar to Captain Olimar's in shape, an average sized nose, and freckles on his cheeks.",
		Tier:            "B+",
		Weight:          79,
		Speed:           1.617,
		NeutralB:        "Pikmin Pluck",
		UpB:             "Winged Pikmin",
		SideB:           "Pikmin Throw",
		DownB:           "Pikmin Order",
		Final_Smash:     "End of Day",
		Image_URL:       "https://www.ssbwiki.com/images/b/b3/Olimar_SSBU.png",
	},
	{
		Name:            "Larry",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "The leader of the Koopalings, with aggressive tendencies to match. He's easily recognized by his tall, blue hair. In New Super Mario Bros. Wii, he makes his appearance in World 1. You might think he's tough, with his blue fireballs and shell spins, but his patterns are actually pretty easy to read.",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/2/29/Bowser_Jr.-Alt1_SSBU.png",
	},
	{
		Name:            "Roy",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "This heavy guy is one of the Koopalings and likes throwing his weight around. His pink sunglasses might not make him seem evil, but the speed he can go from slacker to soldier certainly does. In Super Mario Bros. 3, he causes earthquakes to stop Mario in his tracks, all while attacking with blasts of magic. Nasty stuff!",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/b/bd/Bowser_Jr.-Alt2_SSBU.png",
	},
	{
		Name:            "Wendy",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "Of all the Koopalings, Wendy's the only girl. She's bold, bossy, big headed, and sees Peach and Daisy as her rivals. Despite her tomboyish nature, she's not afraid to show off her feminine side with a pink bow and heels. In New Super Mario Bros. U, she shows off her graceful ice-skating skills with a spin or two.",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/6/6d/Bowser_Jr.-Alt3_SSBU.png",
	},
	{
		Name:            "Iggy",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "One of the Koopalings. Iggy wears black-rimmed glasses, has hair that's sort of pineapplish, and is known for being a bit of a prankster. He talks in a cutesy way but laughs like a maniac. Also, he seems to like taming Chain Chomps, and in New Super Mario Bros. 2, he gets a rampaging Chain Chomp to help him take on Mario.",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/1/1d/Bowser_Jr.-Alt4_SSBU.png",
	},
	{
		Name:            "Morton",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "The biggest of the Koopalings. Morton stands out due to the three strands of hair on his head and...oh, the big star on his face. He's more brawn than brains, and in New Super Mario Bros. 2, he appears in World 4, where he'll stay glued to the spot until you attack him. Maybe he just can't be bothered to move!",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/c/c2/Bowser_Jr.-Alt5_SSBU.png",
	},
	{
		Name:            "Lemmy",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "The smallest and nimblest of the Koopalings, Lemmy is a little rascal with a wacky, childlike look on his face. In New Super Mario Bros. U, he's the boss of World 1 and rides a giant ball while his colorful Mohawk sways in the breeze. Don't underestimate him, though—his ball attacks are trickier than they look!",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/3/38/Bowser_Jr.-Alt6_SSBU.png",
	},
	{
		Name:            "Ludwig",
		Series:          "Super Mario",
		FirstAppearance: "Super Mario Bros. 3",
		Description:     "The cleverest of the Koopalings, easily recognized by his big tufts of hair. He's got a mature air about him, but he likes to show off and can sound a bit pompous. In New Super Mario Bros. Wii, he's the boss of World 7 and torments Mario by firing homing magic blasts and floating too high in the air to be jumped on.",
		Tier:            "D-",
		Weight:          108,
		Speed:           1.566,
		NeutralB:        "Clown Cannon",
		UpB:             "Abandon Ship!",
		SideB:           "Clown Kart Dash",
		DownB:           "Mechakoopa",
		Final_Smash:     "Shadow Mario Paint",
		Image_URL:       "https://www.ssbwiki.com/images/d/d1/Bowser_Jr.-Alt7_SSBU.png",
	},
	{
		Name:            "Hero (Erdrick)",
		Series:          "Dragon Quest",
		FirstAppearance: "Dragon Quest III",
		Description:     `The Hero of Dragon Quest III: The Seeds of Salvation is a fabled, Legendary Hero from the days of lore and the ancient history of Alefgard. Though only appearing in one game, the legacy of The Hero would live on in the "Erdrick Trilogy", so named for the title bestowed upon them and carried forth by their descendants.`,
		Tier:            "B-",
		Weight:          101,
		Speed:           1.84,
		NeutralB:        "Frizz / Frizzle / Kafrizz",
		UpB:             "Woosh / Swoosh / Kaswoosh",
		SideB:           "Zap / Zapple / Kazap",
		DownB:           "Command Selection",
		Final_Smash:     "Gigaslash",
		Image_URL:       "https://www.ssbwiki.com/images/5/5f/DragonQuestIIIRender.png",
	},
	{
		Name:            "Hero (Solo)",
		Series:          "Dragon Quest",
		FirstAppearance: "Dragon Quest IV",
		Description:     "The Hero of Dragon Quest IV is a 17-year-old (18 in the Nintendo DS remake) man or woman prophesied to defeat Psaro and save the world from the rising tide of Demons. As the only person able to wear the Zenithian Equipment, they are the only person in the world capable of doing this. To stop this from happening, Psaro and his minions attempt to eliminate the Hero before they can take up arms, but, fortunately, fail.",
		Tier:            "B-",
		Weight:          101,
		Speed:           1.84,
		NeutralB:        "Frizz / Frizzle / Kafrizz",
		UpB:             "Woosh / Swoosh / Kaswoosh",
		SideB:           "Zap / Zapple / Kazap",
		DownB:           "Command Selection",
		Final_Smash:     "Gigaslash",
		Image_URL:       "https://www.ssbwiki.com/images/e/eb/DragonQuestIVRender.png",
	}, {
		Name:            "Hero (Eight)",
		Series:          "Dragon Quest",
		FirstAppearance: "Dragon Quest VIII",
		Description:     "The Hero of Dragon Quest VIII is an 18-year old low-ranking royal guardsman at Castle Trodain, before becoming a refugee of the kingdom in the prologue. He was one of the small band who survived Dhoulmagus' deadly attack, along with King Trode, Princess Medea and his pet mouse, Munchie. As is the series' tradition, The Hero is a silent protagonist whom the player is meant to project themselves upon, using him as an avatar to explore and interact with the game's world.",
		Tier:            "B-",
		Weight:          101,
		Speed:           1.84,
		NeutralB:        "Frizz / Frizzle / Kafrizz",
		UpB:             "Woosh / Swoosh / Kaswoosh",
		SideB:           "Zap / Zapple / Kazap",
		DownB:           "Command Selection",
		Final_Smash:     "Gigaslash",
		Image_URL:       "https://ssb.wiki.gallery/images/f/fc/DragonQuestVIIIRender.png",
	},
	{
		Name:            "Alex",
		Series:          "Minecraft",
		FirstAppearance: "Minecraft",
		Description:     "Alex can place blocks, which crack and break automatically overtime after placing them. The only blocks he can place are dirt, oak planks, stone, iron blocks, TNT (as down special), and magma blocks (as up smash). Depending on the stage, the dirt can appear as white wool, sand (which does not fall), or ice.",
		Tier:            "S+",
		Weight:          92,
		Speed:           1.45,
		NeutralB:        "Mine / Craft / Create Block",
		UpB:             "Elytra",
		SideB:           "Minecart",
		DownB:           "TNT",
		Final_Smash:     "House of Boom",
		Image_URL:       "https://www.ssbwiki.com/images/b/b6/Alex_SSBU.png",
	},
	{
		Name:            "Zombie",
		Series:          "Minecraft",
		FirstAppearance: "Minecraft",
		Description:     "Zombie can place blocks, which crack and break automatically overtime after placing them. The only blocks he can place are dirt, oak planks, stone, iron blocks, TNT (as down special), and magma blocks (as up smash). Depending on the stage, the dirt can appear as white wool, sand (which does not fall), or ice.",
		Tier:            "S+",
		Weight:          92,
		Speed:           1.45,
		NeutralB:        "Mine / Craft / Create Block",
		UpB:             "Elytra",
		SideB:           "Minecart",
		DownB:           "TNT",
		Final_Smash:     "House of Boom",
		Image_URL:       "https://www.ssbwiki.com/images/0/0f/Zombie_SSBU.png",
	},
	{
		Name:            "Enderman",
		Series:          "Minecraft",
		FirstAppearance: "Minecraft",
		Description:     "Enderman can place blocks, which crack and break automatically overtime after placing them. The only blocks he can place are dirt, oak planks, stone, iron blocks, TNT (as down special), and magma blocks (as up smash). Depending on the stage, the dirt can appear as white wool, sand (which does not fall), or ice.",
		Tier:            "S+",
		Weight:          92,
		Speed:           1.45,
		NeutralB:        "Mine / Craft / Create Block",
		UpB:             "Elytra",
		SideB:           "Minecart",
		DownB:           "TNT",
		Final_Smash:     "House of Boom",
		Image_URL:       "https://www.ssbwiki.com/images/3/3d/Enderman_SSBU.png",
	},
}

func SeedDB(db *gorm.DB) {

	fmt.Println("Starting database seeding...")

	for _, character := range characters {
		err := db.Create(&character).Error
		if err != nil {
			fmt.Printf("Error creating %s: %v\n", character.Name, err)
		} else {
			fmt.Printf("Successfully created %s\n", character.Name)
		}
	}

	fmt.Println("Database seeding completed! :D")
}

func init() {
	utils.LoadEnvVariables()
	utils.ConnectToDB()
}

func main() {
	SeedDB(utils.DB)
}
